project_id = "yqtogmjwkcmeufiwwhba"

[functions.send-welcome-email]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.export-students]
verify_jwt = true

[functions.export-students-analytics]
verify_jwt = false

[functions.translate-content]
verify_jwt = false

[functions.youtube-metadata]
verify_jwt = false

[functions.bulk-update-durations]
verify_jwt = false

[functions.generate-lesson-content]
verify_jwt = false

[functions.generate-lesson-infographics]
verify_jwt = false

[functions.sync-lesson-content]
verify_jwt = false
